{{- range $chartName, $chart := .Values.charts }}
{{- if $chart.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ hasKey $.Values "applicationPrefix" | ternary (printf "%s-%s" $.Values.applicationPrefix (default $chartName $chart.name)) (default $chartName $chart.name) }}
  namespace:  {{ default $.Values.gitOpsNamespace $chart.gitOpsNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ default $.Release.Namespace (default $.Values.destinationNamespace $chart.destinationNamespace) }} 
    server: {{ default $.Values.destinationServer $chart.destinationServer }}
  project: {{ default "default" $chart.project }}
  source:
    {{- if eq (default $.Values.sourceType $chart.sourceType) "git" }}
    path: {{ default $.Values.path $chart.path }}
    targetRevision: {{ default $.Values.targetRevision $chart.targetRevision }}
    {{- else }}
    chart: {{ default $chartName (default $chart.name $chart.repoChart) }}
    targetRevision: {{ default $.Values.chartVersion $chart.chartVersion }}
    {{- end }}
    repoURL: {{ default $.Values.repoURL $chart.repoURL }}
    helm:
      releaseName: {{ default (default $chartName (default $chart.name $chart.repoChart)) $chart.releaseName }}
    {{- if $chart.values }}
      values: |
        {{- toYaml $chart.values | nindent 8 }}
    {{- end }}
    {{- if $chart.valueFiles }}
      valueFiles: |
        {{- toYaml $chart.valueFiles | nindent 8 }}
    {{- end }}
  syncPolicy:
    {{- toYaml (default $.Values.defaultSyncPolicy $chart.syncPolicy) | nindent 4 }}
{{- end }}
{{- end }}