apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}-hl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
