---

postgresql:
  external: false
  ## Use presistent storage
  storage:
    enabled: true
    size: 2Gi
    storageClass: ""
    mountPath: /var/lib/postgresql
  ## Paas Required config
  # storageClass: "aws-efs-tier-c3"
  # labels:
  #   paas.redhat.com/appcode: "ASBL-001"
  user: telescope
  database: telescope
  envVarKeys:
    database: POSTGRES_DB
    user: POSTGRES_USER
    password: POSTGRES_PASSWORD

## If using external db set the host
# host: "example.com"

## Password will be autgeneorated by default
  autogenPassword: true
## If using external instance supply the password
# password: "somepassword"
  port: 5432
  image: docker.io/postgres:13
  autogenImage: docker.io/bitnami/kubectl:latest
  resources:
    limits:
      cpu: 400m
      memory: 596Mi
    requests:
      cpu: 100m
      memory: 128Mi
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
